### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by petey** [Nicolab/atom-package-js-generator#2]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.

```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11)
PackageJsGeneratorView.attach (/Users/petey/.atom/packages/package-js-generator/lib/package-js-generator-view.js:85:7)
```

**Comment by Nicolab** [comment]
Hello,

I fix this as soon as possible.

**Comment by Nicolab** [comment]
See #3
