### ISSUE TITLE
Delete this package

### ISSUE THREAD

**Issue by zedtux** [Nicolab/atom-package-js-generator#8]
Since this package has [an issue](https://github.com/Nicolab/atom-package-js-generator/issues/3) and the official package is handling the Javascript syntax as shown in the screenshot, you can delete this package.

![screen shot 2016-08-08 at 17 38 10](https://cloud.githubusercontent.com/assets/478564/17485763/e400759a-5d8e-11e6-8c5b-2590728c1096.png)

**Comment by Nicolab** [comment]
Great, so I just deleted this package.

R.I.P :ghost:

**Comment by zedtux** [comment]
Maybe you could update the README file in order to inform people about the fact that the official package is taking care of the Vanilla Javascript syntax.

**Comment by Nicolab** [comment]
Updated
